### PR TITLE
Update package naming

### PR DESCRIPTION
**Pull request by SethDavenport**
Now that Angular 4 is in beta, we need to update our package's naming since ng2-redux doesn't make a lot of sense any more.

After conferring with my colleagues we're thinking of also taking the opportunity to move to scoped pages under our github org (`@angular-redux`).

The current idea is as follows:

* ng2-redux -> `@angular-redux/store` [UPDATED, was `core` before]
* ng2-redux-router -> `@angular-redux/router`
* ng2-redux-form -> `@angular-redux/form`

... with potentially others down the line.

This PR starts the process of updating ng2-redux to `@angular-redux/core`.

@dagstuan @clbond if you're cool with this idea, I'll make some PRs for ng2-redux-router, ng2-reux-form, and also work with you to get them published on npm under the new scope.

* [x] get router up and running with latest deps (angular-redux/router#1)
* [x] get form up and running with latest deps
* [x] extract store, form, router examples into an example repo (see [angular-redux/example-app](https://github.com/angular-redux/example-app))
* [x] harmonize ngModule naming across form/store/router
* [ ] harmonize package versions
* [ ] simplify existing in-repo examples to be simple test benches on local code
* [ ] make sure the docs are up to date
* [ ] make sure the code examples are up to date
* [ ] rename GH repos
* [ ] deprecate old npm packages
* [ ] update gitter room

### CODE REVIEW

**Comment by SethDavenport** [comment]
Thanks @dagstuan - I already copied the router code over to angular-redux/router and made you admin.

You shouldn't need to do anything yet - I'm working to get router, core, and form all playing together nicely under the new scope and then I'll publicize the change over.  At that point I'll give you publish rights to the new package too.

**Comment by e-schultz** [comment]
@wbuchwalter any input on this?

**Comment by SethDavenport** [comment]
store also works

**Comment by SethDavenport** [comment]
Put together an example app that combines router, store, and eventually form with the Angular CLI.

**Comment by wbuchwalter** [comment]
Sorry for the delay, I was somewhere remote with no internet for a while.
That makes total sense 👍

**Comment by SethDavenport** [comment]
Awesome @wbuchwalter, thanks.

**Comment by SethDavenport** [comment]
@e-schultz should we harmonize versions across packages? e.g. /store is at 5.1.0, should be bump up form and router to 5.1.0 as well?

**Comment by e-schultz** [comment]
@SethDavenport might as well for this push.

**Comment by SethDavenport** [comment]
Merging what we have now. Checklist moved to #288

**Pull request merged**
