### PR TITLE
Added link to ng2-redux-router

### PR DESCRIPTION
**Pull request by SethDavenport**

### CODE REVIEW

**Comment by SethDavenport** [comment]
@dagstuan FYI. Thanks for a useful package.

**Comment by SethDavenport** [comment]
@dagstuan @e-schultz how would you guys feel about moving ng2-redux-router under the angular-redux organization?

Just an idea.

**Comment by dagstuan** [comment]
@SethDavenport: I would be fine with that. How does one move repos on github?

**Comment by SethDavenport** [comment]
Let me chat with Evan about the mechanics of this next week.

**Comment by e-schultz** [comment]
@dagstuan I can create a repo under the org here and give you admin permissions to it if you like, and can push your code to there.

**Comment by SethDavenport** [comment]
we'd want to make sure the npm package points to the new repo

**Comment by dagstuan** [comment]
@e-schultz, sounds good :) I'm still not sure how I can move the package at npmjs.org to the new repo though, maybe just change the "repository"-field in package.json?

**Pull request merged**
