### PR TITLE
feat(aot): Support AoT - #223

### PR DESCRIPTION
**Pull request by e-schultz**
* Start adding support for AoT
* Add dev dependencies for angular compiler
* Update tsconfig to tell ngc to emit metadata

### CODE REVIEW

**Comment by e-schultz** [comment]
@SethDavenport @dagstuan haven't a chance to test this yet, just starting to get the files generated for AoT

**Comment by spock123** [comment]
I'm tempted to try this out :)

**Comment by SethDavenport** [comment]
@bennett000 has been messing around with AoT quite a bit recently, he might have some insight.

**Comment by bennett000** [comment]
- I think the `@angular/core` bundling system should be adopted.  This means having a `umd` build for legacy consumers and a `module` in `package.json` for ES6/TS consumers
- `@angular/compiler-cli` has been somewhat flakey lately but @watrool was able to get it working on https://github.com/rangle/angular2-starter that starter uses webpack but @watrool used a pre-build step that ran `ngc` and it built!

IIRC there is an issue (I think `@angular/compiler-cli` team is working on fixing) with meta functions being passed to `@select` but that should only affect consumer builds?

**Pull request merged**
