### PR TITLE
Dependency Injection Improvements

### PR DESCRIPTION
**Pull request by SethDavenport**
Reconstituting #67 but from the v3.x branch instead of master.

See discussion in #67; it's still relevant.

Connected to #40 
Connected to #41 
Connected to #43

### CODE REVIEW

**Comment by SethDavenport** [comment]
* [ ] unit test for 2 calls to attach - second one should fail invariant.
* [ ] unit test to ensure that applicationRef.tick is called as expected.
* [ ] middleware example (including README update)
* [ ] bring in example `@select` implementation from #40 
* [x] version bump to 3.0.0?

**Comment by SethDavenport** [comment]
@kosz @e-schultz @wbuchwalter

**Comment by SethDavenport** [comment]
@e-schultz @kosz @wbuchwalter : if we're in agreement about this approach, this PR is now ready for merging into the 3.x branch.

We can then leverage it for the decorator work.

**Comment by e-schultz** [comment]
@SethDavenport @kosz I'm fine with merging this in and experimenting with it - it's a good starting point. Even if we end up not sticking with it, curious to give it a try. go-go 3.x@expirmental ;)

**Pull request merged**
