### PR TITLE
[WIP - Don't merge] Dependency Injection Improvements

### PR DESCRIPTION
**Pull request by SethDavenport**
Updated API to fit better with Angular 2 DI.

Connected to #43 
Connected to #41 
Connected to #40

The main change here is to delay configuring the
redux store until after the app has bootstrapped.
So instead of doing:

```typescript
import { provider } from 'ng2-redux';

bootstrap(App, [
  provider(configureStore()) ]);
```

We instead do:

```typescript
import { NgRedux } from 'ng2-redux';

bootstrap(App, [ NgRedux ]);

@Component({
  // ...
})
class App {
  constructor(private ngRedux: NgRedux) {
    ngRedux.attach(configureStore());
  }
}
```

This is desirable for two reasons:

1. We can now inject angular services into NgRedux
itself
2. We can now inject angular services into redux
middleware and store enhancers.

(1) is needed to resolve the issue with redux
dev tools store updates happening outside the angular
zone.  We need to be able to do an `applicationRef.tick()`
on state update or the Angular UI doesn't respond to
dev tool actions.  Handling it internally this way is
preferable to making the end user remember to hook
it up manually.

(2) is a major feature that is currently impossible
in the old architecture, (unless you do [major hax](https://github.com/angular-redux/ng2-redux#using-angular-2-services-in-your-middleware)) since previously the middleware
needed to be applied to the store before the Angular DI
was bootstrapped.

I think this approach is much more in line with how
people expect Angular 2 DI to function, and resolves
a number of other thorny init problems.

However it does represent an API change, and thus
will require a major version bump if adopted.

Also in this commit:
- some minor code cleanup
- switch to the more size-efficient rxjs import pattern
- marked the `select` api as deprecated.

### CODE REVIEW

**Comment by SethDavenport** [comment]
Also removed the `store` parameter from `ngRedux.observableFromStore()` since it represents a leaky abstraction. Calling this method with no arguments now gets you an observable for the entire state.

**Comment by SethDavenport** [comment]
@e-schultz @kosz - I'd like your take on this.  I think it's needed to handle DI correctly and is the correct approach for an Angular 2 binding.  However I also don't want to derail your work on decorators.

I'm thinking it doesn't really change much for the decorator stuff, just means it will take a bit longer to initialize.

**Comment by SethDavenport** [comment]
I will soon add some examples of Dependency-Injected middleware to prove the other use cases. Stay tuned.

Finally, I'm a bit torn between attaching the store like this:

```typescript
// Configure the store in client code and then pass it in
class NgRedux.attach(configureStore());
```

or actually configuring the store in ngRedux as follows:

```typescript
// Pass in named, optional parameters and configure the store internally to ngRedux.
ngRedux.configureStore({ 
  reducers, 
  middleware, 
  enhancers, 
  initialState
});
```

I like the explicit nature of the second option - also reduces some of the confusion newcomers often have to the whole `configureStore(foo)(bar)` etc.

**Comment by SethDavenport** [comment]
Actually I think this __helps__ the selector approach.

You can now create the `appInjector$` internally to ng2-redux and never expose it.  Now that the NgRedux service is dependency injected with `ApplicationRef` you can just go in NgRedux's constructor and do:

```typescript
constructor(private applicationRef: ApplicationRef) {
  appInjector$.next(applicationRef.injector);
}
```

Done - automagic initialization: no ugly `bootstrap.then` required.  The user has fewer things to remember to hook up.

**Comment by SethDavenport** [comment]
[ ] unit test for 2 calls to attach - second one should fail invariant.
[ ] unit test to ensure that applicationRef.tick is called as expected.
[ ] middleware example (including README update)
[ ] bring in example @select implementation from #40 
[ ] version bump to 3.0.0?

**Comment by e-schultz** [comment]
@SethDavenport good work, although I'm also of mixed opinions on this - but mostly leaning in favour, especially if it will allow for more flexibility with being able to configure middleware/etc.

The `.then(appInjector)` does feel rather, hacky. On the other hand, something feels weird about needing to bootstrap redux in your root component. Both are solutions that I'm not the happiest with, but considering how angular bootstraps and initializes things, I guess it's a matter of 'lesser of two evils'. 

Wondering how this would impact the testability of a component using ngRedux.

This would require a version bump - but at least the refactor required to upgrade would be very minimal.

@wbuchwalter thoughts?

**Comment by kosz** [comment]
So I'm curious what @wbuchwalter does think of this approach as well, since it could impact how I write the decorators implementation. 

I also have a work around for this using that preAugmentFunction idea on ngOnInit functions of classes that get decorated with @select. That approach is also hacky however it does not require the user to hack, instead it keeps the hackyness hidden away. 

Alternatively maybe using @SethDavenport 's idea here and building the @select decorator on top of this  could also be an interesting option.

**Comment by SethDavenport** [comment]
Re-creating PR against the v3.x branch.

**Pull request closed without merging**
