### PR TITLE
Using Angular2 file naming styleguide

### PR DESCRIPTION
**Pull request by francesco-strazzullo**
Some of the file in the utils directory has camel case notation, other the snake notation. I've change everything to the Angular2 Styleguide (with dashes)

### CODE REVIEW

**Comment by SethDavenport** [comment]
Thanks - this is good cleanup. Can you resolve the conflicts?

**Comment by e-schultz** [comment]
👍 if you can fix the conflicts I'll merge it in, thanks

**Comment by francesco-strazzullo** [comment]
Ok I will fix the conficts right away

**Comment by francesco-strazzullo** [comment]
@e-schultz @SethDavenport conflicts resolved!

**Pull request merged**
