### PR TITLE
fix(package.json): add redux as dependencies

### PR DESCRIPTION
**Pull request by jmfrancois**
Redux is a dependency. devDependencies are only fetch if you are working on ng2-redux.
If ng2-redux is a dependency of a project the project will not fetch redux.

### CODE REVIEW

**Comment by SethDavenport** [comment]
@e-schultz maybe it should actually be a peer dependency? Espectially when it comes to using ng2-redux from SystemJS

**Comment by jmfrancois** [comment]
True it should be a peerDependencies

**Comment by SethDavenport** [comment]
Thanks @jmfrancois 

@e-schultz if you're OK with the change I'll merge it.

**Comment by e-schultz** [comment]
@jmfrancois just merged in another PR that updated things to RC3, can you fix the conflicts then I'll merge it in.

**Comment by jmfrancois** [comment]
Done @e-schultz

**Pull request merged**
