### PR TITLE
[Fixes #181] Upgrade to TypeScript 2.0.0, Cleanup

### LINKED ISSUE #181: update to Typescript 2
This will likely involve:

* updating the compiler
* getting rid of typings in favour of the new `@types` thing.
* removing `typings` from peer deps

### PR DESCRIPTION
**Pull request by SethDavenport**

### CODE REVIEW

**Comment by SethDavenport** [comment]
Having some issues with the unit tests.

**Comment by SethDavenport** [comment]
Test now fine - example app is giving me trouble.

**Comment by SethDavenport** [comment]
This is now working fine.  Major changes:

* Update to typescript 2.0.0 for both ng2-redux and the example
* Removed a lot of unnecessary deps from both projects
* Fixed some type errors where 2.0.0 is stricter than 1.8
* Simplified the unit test command
* Simplified the build - we now skip transpilation of spec files instead of transpiling and then deleting them.
* That last point allows tests to be colocated with their code, which is where they should be :)

**Comment by e-schultz** [comment]
@SethDavenport 👍 after you fix the merge conflict is fixed

**Pull request merged**
